name: ci

on:
  push:
    branches:
    - '*'
    - '*/*'
    - '**'

jobs:
  ubuntu:
    name: Compile & Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install latest rust toolchain
      uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
      with:
        toolchain: "1.78.0"
        targets: ${{ matrix.target }}

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Test
      run: make test

    - name: Build
      run: make debug

    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

  macos:
    name: Compile & Test
    strategy:
      matrix:
        os: [macos-latest]
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install latest rust toolchain
      uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
      with:
        toolchain: "1.78.0"
        targets: ${{ matrix.target }}

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Test
      run: make test

    - name: Build
      run: make debug

    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
